FROM node:6.11.0-alpine

ENV NODE_ENV development

COPY package.json /code/package.json
COPY yarn.lock /code/yarn.lock
RUN cd /code && yarn install

COPY . /code
WORKDIR /code

EXPOSE 8080 8082

CMD ["yarn","run","dev"]
