version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-local
    ports:
      - "8080:8080"
      - "8082:8082"
    depends_on:
      - db
    volumes:
      - ./src:/code/src
    environment:
      - HUBSPOT_API_KEY=b0dfb14f-246d-449d-b3a2-309e10434f45
  db:
    image: postgres:alpine
    ports:
      - "8081:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sessions_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sessions_app
