version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-local
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/code
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sessions_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sessions_app
